/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASemisepAList extends PAList
{
    private TId _id1_;
    private TAssignment _assignment_;
    private TId _id2_;
    private TSemicolon _semicolon_;
    private PAList _aList_;

    public ASemisepAList()
    {
        // Constructor
    }

    public ASemisepAList(
        @SuppressWarnings("hiding") TId _id1_,
        @SuppressWarnings("hiding") TAssignment _assignment_,
        @SuppressWarnings("hiding") TId _id2_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PAList _aList_)
    {
        // Constructor
        setId1(_id1_);

        setAssignment(_assignment_);

        setId2(_id2_);

        setSemicolon(_semicolon_);

        setAList(_aList_);

    }

    @Override
    public Object clone()
    {
        return new ASemisepAList(
            cloneNode(this._id1_),
            cloneNode(this._assignment_),
            cloneNode(this._id2_),
            cloneNode(this._semicolon_),
            cloneNode(this._aList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASemisepAList(this);
    }

    public TId getId1()
    {
        return this._id1_;
    }

    public void setId1(TId node)
    {
        if(this._id1_ != null)
        {
            this._id1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id1_ = node;
    }

    public TAssignment getAssignment()
    {
        return this._assignment_;
    }

    public void setAssignment(TAssignment node)
    {
        if(this._assignment_ != null)
        {
            this._assignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignment_ = node;
    }

    public TId getId2()
    {
        return this._id2_;
    }

    public void setId2(TId node)
    {
        if(this._id2_ != null)
        {
            this._id2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id2_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PAList getAList()
    {
        return this._aList_;
    }

    public void setAList(PAList node)
    {
        if(this._aList_ != null)
        {
            this._aList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id1_)
            + toString(this._assignment_)
            + toString(this._id2_)
            + toString(this._semicolon_)
            + toString(this._aList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id1_ == child)
        {
            this._id1_ = null;
            return;
        }

        if(this._assignment_ == child)
        {
            this._assignment_ = null;
            return;
        }

        if(this._id2_ == child)
        {
            this._id2_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._aList_ == child)
        {
            this._aList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id1_ == oldChild)
        {
            setId1((TId) newChild);
            return;
        }

        if(this._assignment_ == oldChild)
        {
            setAssignment((TAssignment) newChild);
            return;
        }

        if(this._id2_ == oldChild)
        {
            setId2((TId) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._aList_ == oldChild)
        {
            setAList((PAList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
